from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.book import Book
from openapi_server import util

from openapi_server.models.book import Book  # noqa: E501

class ApiBooksGet200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, books=None, total=None, page=None, pages=None):  # noqa: E501
        """ApiBooksGet200Response - a model defined in OpenAPI

        :param books: The books of this ApiBooksGet200Response.  # noqa: E501
        :type books: List[Book]
        :param total: The total of this ApiBooksGet200Response.  # noqa: E501
        :type total: int
        :param page: The page of this ApiBooksGet200Response.  # noqa: E501
        :type page: int
        :param pages: The pages of this ApiBooksGet200Response.  # noqa: E501
        :type pages: int
        """
        self.openapi_types = {
            'books': List[Book],
            'total': int,
            'page': int,
            'pages': int
        }

        self.attribute_map = {
            'books': 'books',
            'total': 'total',
            'page': 'page',
            'pages': 'pages'
        }

        self._books = books
        self._total = total
        self._page = page
        self._pages = pages

    @classmethod
    def from_dict(cls, dikt) -> 'ApiBooksGet200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _api_books_get_200_response of this ApiBooksGet200Response.  # noqa: E501
        :rtype: ApiBooksGet200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def books(self) -> List[Book]:
        """Gets the books of this ApiBooksGet200Response.


        :return: The books of this ApiBooksGet200Response.
        :rtype: List[Book]
        """
        return self._books

    @books.setter
    def books(self, books: List[Book]):
        """Sets the books of this ApiBooksGet200Response.


        :param books: The books of this ApiBooksGet200Response.
        :type books: List[Book]
        """

        self._books = books

    @property
    def total(self) -> int:
        """Gets the total of this ApiBooksGet200Response.


        :return: The total of this ApiBooksGet200Response.
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total: int):
        """Sets the total of this ApiBooksGet200Response.


        :param total: The total of this ApiBooksGet200Response.
        :type total: int
        """

        self._total = total

    @property
    def page(self) -> int:
        """Gets the page of this ApiBooksGet200Response.


        :return: The page of this ApiBooksGet200Response.
        :rtype: int
        """
        return self._page

    @page.setter
    def page(self, page: int):
        """Sets the page of this ApiBooksGet200Response.


        :param page: The page of this ApiBooksGet200Response.
        :type page: int
        """

        self._page = page

    @property
    def pages(self) -> int:
        """Gets the pages of this ApiBooksGet200Response.


        :return: The pages of this ApiBooksGet200Response.
        :rtype: int
        """
        return self._pages

    @pages.setter
    def pages(self, pages: int):
        """Sets the pages of this ApiBooksGet200Response.


        :param pages: The pages of this ApiBooksGet200Response.
        :type pages: int
        """

        self._pages = pages
