from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ApiBooksPost201Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, book_id=None):  # noqa: E501
        """ApiBooksPost201Response - a model defined in OpenAPI

        :param book_id: The book_id of this ApiBooksPost201Response.  # noqa: E501
        :type book_id: int
        """
        self.openapi_types = {
            'book_id': int
        }

        self.attribute_map = {
            'book_id': 'book_id'
        }

        self._book_id = book_id

    @classmethod
    def from_dict(cls, dikt) -> 'ApiBooksPost201Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _api_books_post_201_response of this ApiBooksPost201Response.  # noqa: E501
        :rtype: ApiBooksPost201Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def book_id(self) -> int:
        """Gets the book_id of this ApiBooksPost201Response.


        :return: The book_id of this ApiBooksPost201Response.
        :rtype: int
        """
        return self._book_id

    @book_id.setter
    def book_id(self, book_id: int):
        """Sets the book_id of this ApiBooksPost201Response.


        :param book_id: The book_id of this ApiBooksPost201Response.
        :type book_id: int
        """

        self._book_id = book_id
