from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class Book(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, book_id=None, title=None, genre=None, published_year=None, authors=None, total_copies=None, available_copies=None):  # noqa: E501
        """Book - a model defined in OpenAPI

        :param book_id: The book_id of this Book.  # noqa: E501
        :type book_id: int
        :param title: The title of this Book.  # noqa: E501
        :type title: str
        :param genre: The genre of this Book.  # noqa: E501
        :type genre: str
        :param published_year: The published_year of this Book.  # noqa: E501
        :type published_year: int
        :param authors: The authors of this Book.  # noqa: E501
        :type authors: List[str]
        :param total_copies: The total_copies of this Book.  # noqa: E501
        :type total_copies: int
        :param available_copies: The available_copies of this Book.  # noqa: E501
        :type available_copies: int
        """
        self.openapi_types = {
            'book_id': int,
            'title': str,
            'genre': str,
            'published_year': int,
            'authors': List[str],
            'total_copies': int,
            'available_copies': int
        }

        self.attribute_map = {
            'book_id': 'book_id',
            'title': 'title',
            'genre': 'genre',
            'published_year': 'published_year',
            'authors': 'authors',
            'total_copies': 'total_copies',
            'available_copies': 'available_copies'
        }

        self._book_id = book_id
        self._title = title
        self._genre = genre
        self._published_year = published_year
        self._authors = authors
        self._total_copies = total_copies
        self._available_copies = available_copies

    @classmethod
    def from_dict(cls, dikt) -> 'Book':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Book of this Book.  # noqa: E501
        :rtype: Book
        """
        return util.deserialize_model(dikt, cls)

    @property
    def book_id(self) -> int:
        """Gets the book_id of this Book.


        :return: The book_id of this Book.
        :rtype: int
        """
        return self._book_id

    @book_id.setter
    def book_id(self, book_id: int):
        """Sets the book_id of this Book.


        :param book_id: The book_id of this Book.
        :type book_id: int
        """

        self._book_id = book_id

    @property
    def title(self) -> str:
        """Gets the title of this Book.


        :return: The title of this Book.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this Book.


        :param title: The title of this Book.
        :type title: str
        """

        self._title = title

    @property
    def genre(self) -> str:
        """Gets the genre of this Book.


        :return: The genre of this Book.
        :rtype: str
        """
        return self._genre

    @genre.setter
    def genre(self, genre: str):
        """Sets the genre of this Book.


        :param genre: The genre of this Book.
        :type genre: str
        """

        self._genre = genre

    @property
    def published_year(self) -> int:
        """Gets the published_year of this Book.


        :return: The published_year of this Book.
        :rtype: int
        """
        return self._published_year

    @published_year.setter
    def published_year(self, published_year: int):
        """Sets the published_year of this Book.


        :param published_year: The published_year of this Book.
        :type published_year: int
        """

        self._published_year = published_year

    @property
    def authors(self) -> List[str]:
        """Gets the authors of this Book.


        :return: The authors of this Book.
        :rtype: List[str]
        """
        return self._authors

    @authors.setter
    def authors(self, authors: List[str]):
        """Sets the authors of this Book.


        :param authors: The authors of this Book.
        :type authors: List[str]
        """

        self._authors = authors

    @property
    def total_copies(self) -> int:
        """Gets the total_copies of this Book.


        :return: The total_copies of this Book.
        :rtype: int
        """
        return self._total_copies

    @total_copies.setter
    def total_copies(self, total_copies: int):
        """Sets the total_copies of this Book.


        :param total_copies: The total_copies of this Book.
        :type total_copies: int
        """

        self._total_copies = total_copies

    @property
    def available_copies(self) -> int:
        """Gets the available_copies of this Book.


        :return: The available_copies of this Book.
        :rtype: int
        """
        return self._available_copies

    @available_copies.setter
    def available_copies(self, available_copies: int):
        """Sets the available_copies of this Book.


        :param available_copies: The available_copies of this Book.
        :type available_copies: int
        """

        self._available_copies = available_copies
