from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class BookDetailAllOfCopies(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, book_copy_id=None, available=None):  # noqa: E501
        """BookDetailAllOfCopies - a model defined in OpenAPI

        :param book_copy_id: The book_copy_id of this BookDetailAllOfCopies.  # noqa: E501
        :type book_copy_id: int
        :param available: The available of this BookDetailAllOfCopies.  # noqa: E501
        :type available: bool
        """
        self.openapi_types = {
            'book_copy_id': int,
            'available': bool
        }

        self.attribute_map = {
            'book_copy_id': 'book_copy_id',
            'available': 'available'
        }

        self._book_copy_id = book_copy_id
        self._available = available

    @classmethod
    def from_dict(cls, dikt) -> 'BookDetailAllOfCopies':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BookDetail_allOf_copies of this BookDetailAllOfCopies.  # noqa: E501
        :rtype: BookDetailAllOfCopies
        """
        return util.deserialize_model(dikt, cls)

    @property
    def book_copy_id(self) -> int:
        """Gets the book_copy_id of this BookDetailAllOfCopies.


        :return: The book_copy_id of this BookDetailAllOfCopies.
        :rtype: int
        """
        return self._book_copy_id

    @book_copy_id.setter
    def book_copy_id(self, book_copy_id: int):
        """Sets the book_copy_id of this BookDetailAllOfCopies.


        :param book_copy_id: The book_copy_id of this BookDetailAllOfCopies.
        :type book_copy_id: int
        """

        self._book_copy_id = book_copy_id

    @property
    def available(self) -> bool:
        """Gets the available of this BookDetailAllOfCopies.


        :return: The available of this BookDetailAllOfCopies.
        :rtype: bool
        """
        return self._available

    @available.setter
    def available(self, available: bool):
        """Sets the available of this BookDetailAllOfCopies.


        :param available: The available of this BookDetailAllOfCopies.
        :type available: bool
        """

        self._available = available
