from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class BookUpdate(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, title=None, genre=None, published_year=None, authors=None, add_copies=None, remove_copy_ids=None):  # noqa: E501
        """BookUpdate - a model defined in OpenAPI

        :param title: The title of this BookUpdate.  # noqa: E501
        :type title: str
        :param genre: The genre of this BookUpdate.  # noqa: E501
        :type genre: str
        :param published_year: The published_year of this BookUpdate.  # noqa: E501
        :type published_year: int
        :param authors: The authors of this BookUpdate.  # noqa: E501
        :type authors: List[str]
        :param add_copies: The add_copies of this BookUpdate.  # noqa: E501
        :type add_copies: int
        :param remove_copy_ids: The remove_copy_ids of this BookUpdate.  # noqa: E501
        :type remove_copy_ids: List[int]
        """
        self.openapi_types = {
            'title': str,
            'genre': str,
            'published_year': int,
            'authors': List[str],
            'add_copies': int,
            'remove_copy_ids': List[int]
        }

        self.attribute_map = {
            'title': 'title',
            'genre': 'genre',
            'published_year': 'published_year',
            'authors': 'authors',
            'add_copies': 'add_copies',
            'remove_copy_ids': 'remove_copy_ids'
        }

        self._title = title
        self._genre = genre
        self._published_year = published_year
        self._authors = authors
        self._add_copies = add_copies
        self._remove_copy_ids = remove_copy_ids

    @classmethod
    def from_dict(cls, dikt) -> 'BookUpdate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BookUpdate of this BookUpdate.  # noqa: E501
        :rtype: BookUpdate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self) -> str:
        """Gets the title of this BookUpdate.


        :return: The title of this BookUpdate.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this BookUpdate.


        :param title: The title of this BookUpdate.
        :type title: str
        """

        self._title = title

    @property
    def genre(self) -> str:
        """Gets the genre of this BookUpdate.


        :return: The genre of this BookUpdate.
        :rtype: str
        """
        return self._genre

    @genre.setter
    def genre(self, genre: str):
        """Sets the genre of this BookUpdate.


        :param genre: The genre of this BookUpdate.
        :type genre: str
        """

        self._genre = genre

    @property
    def published_year(self) -> int:
        """Gets the published_year of this BookUpdate.


        :return: The published_year of this BookUpdate.
        :rtype: int
        """
        return self._published_year

    @published_year.setter
    def published_year(self, published_year: int):
        """Sets the published_year of this BookUpdate.


        :param published_year: The published_year of this BookUpdate.
        :type published_year: int
        """

        self._published_year = published_year

    @property
    def authors(self) -> List[str]:
        """Gets the authors of this BookUpdate.


        :return: The authors of this BookUpdate.
        :rtype: List[str]
        """
        return self._authors

    @authors.setter
    def authors(self, authors: List[str]):
        """Sets the authors of this BookUpdate.


        :param authors: The authors of this BookUpdate.
        :type authors: List[str]
        """

        self._authors = authors

    @property
    def add_copies(self) -> int:
        """Gets the add_copies of this BookUpdate.


        :return: The add_copies of this BookUpdate.
        :rtype: int
        """
        return self._add_copies

    @add_copies.setter
    def add_copies(self, add_copies: int):
        """Sets the add_copies of this BookUpdate.


        :param add_copies: The add_copies of this BookUpdate.
        :type add_copies: int
        """

        self._add_copies = add_copies

    @property
    def remove_copy_ids(self) -> List[int]:
        """Gets the remove_copy_ids of this BookUpdate.


        :return: The remove_copy_ids of this BookUpdate.
        :rtype: List[int]
        """
        return self._remove_copy_ids

    @remove_copy_ids.setter
    def remove_copy_ids(self, remove_copy_ids: List[int]):
        """Sets the remove_copy_ids of this BookUpdate.


        :param remove_copy_ids: The remove_copy_ids of this BookUpdate.
        :type remove_copy_ids: List[int]
        """

        self._remove_copy_ids = remove_copy_ids
