from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class BookCreate(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, title=None, genre=None, published_year=None, authors=None, copies=None):  # noqa: E501
        """BookCreate - a model defined in OpenAPI

        :param title: The title of this BookCreate.  # noqa: E501
        :type title: str
        :param genre: The genre of this BookCreate.  # noqa: E501
        :type genre: str
        :param published_year: The published_year of this BookCreate.  # noqa: E501
        :type published_year: int
        :param authors: The authors of this BookCreate.  # noqa: E501
        :type authors: List[str]
        :param copies: The copies of this BookCreate.  # noqa: E501
        :type copies: int
        """
        self.openapi_types = {
            'title': str,
            'genre': str,
            'published_year': int,
            'authors': List[str],
            'copies': int
        }

        self.attribute_map = {
            'title': 'title',
            'genre': 'genre',
            'published_year': 'published_year',
            'authors': 'authors',
            'copies': 'copies'
        }

        self._title = title
        self._genre = genre
        self._published_year = published_year
        self._authors = authors
        self._copies = copies

    @classmethod
    def from_dict(cls, dikt) -> 'BookCreate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The BookCreate of this BookCreate.  # noqa: E501
        :rtype: BookCreate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self) -> str:
        """Gets the title of this BookCreate.


        :return: The title of this BookCreate.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this BookCreate.


        :param title: The title of this BookCreate.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def genre(self) -> str:
        """Gets the genre of this BookCreate.


        :return: The genre of this BookCreate.
        :rtype: str
        """
        return self._genre

    @genre.setter
    def genre(self, genre: str):
        """Sets the genre of this BookCreate.


        :param genre: The genre of this BookCreate.
        :type genre: str
        """

        self._genre = genre

    @property
    def published_year(self) -> int:
        """Gets the published_year of this BookCreate.


        :return: The published_year of this BookCreate.
        :rtype: int
        """
        return self._published_year

    @published_year.setter
    def published_year(self, published_year: int):
        """Sets the published_year of this BookCreate.


        :param published_year: The published_year of this BookCreate.
        :type published_year: int
        """

        self._published_year = published_year

    @property
    def authors(self) -> List[str]:
        """Gets the authors of this BookCreate.


        :return: The authors of this BookCreate.
        :rtype: List[str]
        """
        return self._authors

    @authors.setter
    def authors(self, authors: List[str]):
        """Sets the authors of this BookCreate.


        :param authors: The authors of this BookCreate.
        :type authors: List[str]
        """

        self._authors = authors

    @property
    def copies(self) -> int:
        """Gets the copies of this BookCreate.


        :return: The copies of this BookCreate.
        :rtype: int
        """
        return self._copies

    @copies.setter
    def copies(self, copies: int):
        """Sets the copies of this BookCreate.


        :param copies: The copies of this BookCreate.
        :type copies: int
        """

        self._copies = copies
